[package]
name = "gdrust_macros"
version = "0.1.0"
authors = ["gdrust developers"]
edition = "2018"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"]}

[dev-dependencies]
gdnative = "0.9"

[lib]
proc-macro = true